# yaml有层次，可以继承
server:
  port: 80
  servlet:
    context-path: /boot

lucas:
  root:
    username: root
    password: 123456
    gfs:
      - 流萤
      - 知更鸟
      - 花火

#spring:
#  profiles:
#    active: test, dev

#激活外部的配置 application-test application-dev
#外部的配置的key和application的key重复 外部的覆盖内部


